Document.title = "DOM in javascipt";

document.getElementById("MRCET").innerHTML="Hello,World!";

document.getElementById("para").style.color="blue";


document.getElementById("para").style.fontsize="30px";

document.getElementById("MR").style.color="red";

document.getElementById("MR").style.fontSize="30px";
document.getElementsByName("ds")[0].style.color="red";

document.body.style.backgroundcolor ="light green";
